ceilometer:
    SNMP_COMMUNITY: public123
    MONGODB_CEILOMETER_USER: ceilometer
    MONGODB_CEILOMETER_PASS: 'ptfM1RT880kPIAzN'
    MONGODB_CEILOMETER_DBNAME: ceilometer
    INFLUXDB_CEILOMETER_USER: root
    INFLUXDB_CEILOMETER_PASS: root
    INFLUXDB_CEILOMETER_DBNAME: ceilometer
    AUTH_ADMIN_CEILOMETER_USER: ceilometer
    AUTH_ADMIN_CEILOMETER_PASS: 'ZHrXibvk0Z3yWtgc'
    METERING_SECRET: 'iWjNbKqaXyRuJIG6'
