nova:
    MYSQL_NOVA_USER: nova
    MYSQL_NOVA_PASS: 'BFGco8o1HWI6VXev' 
    MYSQL_NOVA_DBNAME: nova
    AUTH_ADMIN_NOVA_USER: nova
    AUTH_ADMIN_NOVA_PASS: 'TzUMo5LeoBePveCB'
    METADATA_PROXY_SECRET: 'lsSzNZotpsN1zrH4'
    VNC_ENABLED: True
